# Generated by Django 5.1 on 2025-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Customer's phone number for contact.", max_length=20, null=True),
        ),
    ]
