# Generated by Django 5.1 on 2025-02-26 18:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_order_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='myapp_booki_date_8ff489_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'meal_type', 'slot'], name='myapp_booki_date_ed0630_idx'),
        ),
    ]
